# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.28

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/m/Code/cpp/EarthSim

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/m/Code/cpp/EarthSim

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# Special rule for the target list_install_components
list_install_components:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Available install components are: \"Unspecified\""
.PHONY : list_install_components

# Special rule for the target list_install_components
list_install_components/fast: list_install_components
.PHONY : list_install_components/fast

# Special rule for the target install
install: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Install the project..."
	/usr/bin/cmake -P cmake_install.cmake
.PHONY : install

# Special rule for the target install
install/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Install the project..."
	/usr/bin/cmake -P cmake_install.cmake
.PHONY : install/fast

# Special rule for the target install/local
install/local: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Installing only the local directory..."
	/usr/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local

# Special rule for the target install/local
install/local/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Installing only the local directory..."
	/usr/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local/fast

# Special rule for the target install/strip
install/strip: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Installing the project stripped..."
	/usr/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip

# Special rule for the target install/strip
install/strip/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Installing the project stripped..."
	/usr/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/m/Code/cpp/EarthSim/CMakeFiles /home/m/Code/cpp/EarthSim//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/m/Code/cpp/EarthSim/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named earth_sim

# Build rule for target.
earth_sim: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 earth_sim
.PHONY : earth_sim

# fast build rule for target.
earth_sim/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/earth_sim.dir/build.make CMakeFiles/earth_sim.dir/build
.PHONY : earth_sim/fast

#=============================================================================
# Target rules for targets named wgs_test

# Build rule for target.
wgs_test: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 wgs_test
.PHONY : wgs_test

# fast build rule for target.
wgs_test/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/wgs_test.dir/build.make CMakeFiles/wgs_test.dir/build
.PHONY : wgs_test/fast

#=============================================================================
# Target rules for targets named loader_example

# Build rule for target.
loader_example: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 loader_example
.PHONY : loader_example

# fast build rule for target.
loader_example/fast:
	$(MAKE) $(MAKESILENT) -f include/tinygltf/CMakeFiles/loader_example.dir/build.make include/tinygltf/CMakeFiles/loader_example.dir/build
.PHONY : loader_example/fast

#=============================================================================
# Target rules for targets named tinygltf

# Build rule for target.
tinygltf: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 tinygltf
.PHONY : tinygltf

# fast build rule for target.
tinygltf/fast:
	$(MAKE) $(MAKESILENT) -f include/tinygltf/CMakeFiles/tinygltf.dir/build.make include/tinygltf/CMakeFiles/tinygltf.dir/build
.PHONY : tinygltf/fast

include/Cameras/FirstPersonCamera.o: include/Cameras/FirstPersonCamera.cpp.o
.PHONY : include/Cameras/FirstPersonCamera.o

# target to build an object file
include/Cameras/FirstPersonCamera.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/earth_sim.dir/build.make CMakeFiles/earth_sim.dir/include/Cameras/FirstPersonCamera.cpp.o
.PHONY : include/Cameras/FirstPersonCamera.cpp.o

include/Cameras/FirstPersonCamera.i: include/Cameras/FirstPersonCamera.cpp.i
.PHONY : include/Cameras/FirstPersonCamera.i

# target to preprocess a source file
include/Cameras/FirstPersonCamera.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/earth_sim.dir/build.make CMakeFiles/earth_sim.dir/include/Cameras/FirstPersonCamera.cpp.i
.PHONY : include/Cameras/FirstPersonCamera.cpp.i

include/Cameras/FirstPersonCamera.s: include/Cameras/FirstPersonCamera.cpp.s
.PHONY : include/Cameras/FirstPersonCamera.s

# target to generate assembly for a file
include/Cameras/FirstPersonCamera.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/earth_sim.dir/build.make CMakeFiles/earth_sim.dir/include/Cameras/FirstPersonCamera.cpp.s
.PHONY : include/Cameras/FirstPersonCamera.cpp.s

include/Engine.o: include/Engine.cpp.o
.PHONY : include/Engine.o

# target to build an object file
include/Engine.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/earth_sim.dir/build.make CMakeFiles/earth_sim.dir/include/Engine.cpp.o
.PHONY : include/Engine.cpp.o

include/Engine.i: include/Engine.cpp.i
.PHONY : include/Engine.i

# target to preprocess a source file
include/Engine.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/earth_sim.dir/build.make CMakeFiles/earth_sim.dir/include/Engine.cpp.i
.PHONY : include/Engine.cpp.i

include/Engine.s: include/Engine.cpp.s
.PHONY : include/Engine.s

# target to generate assembly for a file
include/Engine.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/earth_sim.dir/build.make CMakeFiles/earth_sim.dir/include/Engine.cpp.s
.PHONY : include/Engine.cpp.s

include/Objects/Object.o: include/Objects/Object.cpp.o
.PHONY : include/Objects/Object.o

# target to build an object file
include/Objects/Object.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/earth_sim.dir/build.make CMakeFiles/earth_sim.dir/include/Objects/Object.cpp.o
.PHONY : include/Objects/Object.cpp.o

include/Objects/Object.i: include/Objects/Object.cpp.i
.PHONY : include/Objects/Object.i

# target to preprocess a source file
include/Objects/Object.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/earth_sim.dir/build.make CMakeFiles/earth_sim.dir/include/Objects/Object.cpp.i
.PHONY : include/Objects/Object.cpp.i

include/Objects/Object.s: include/Objects/Object.cpp.s
.PHONY : include/Objects/Object.s

# target to generate assembly for a file
include/Objects/Object.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/earth_sim.dir/build.make CMakeFiles/earth_sim.dir/include/Objects/Object.cpp.s
.PHONY : include/Objects/Object.cpp.s

include/Utils/Console.o: include/Utils/Console.cpp.o
.PHONY : include/Utils/Console.o

# target to build an object file
include/Utils/Console.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/earth_sim.dir/build.make CMakeFiles/earth_sim.dir/include/Utils/Console.cpp.o
.PHONY : include/Utils/Console.cpp.o

include/Utils/Console.i: include/Utils/Console.cpp.i
.PHONY : include/Utils/Console.i

# target to preprocess a source file
include/Utils/Console.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/earth_sim.dir/build.make CMakeFiles/earth_sim.dir/include/Utils/Console.cpp.i
.PHONY : include/Utils/Console.cpp.i

include/Utils/Console.s: include/Utils/Console.cpp.s
.PHONY : include/Utils/Console.s

# target to generate assembly for a file
include/Utils/Console.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/earth_sim.dir/build.make CMakeFiles/earth_sim.dir/include/Utils/Console.cpp.s
.PHONY : include/Utils/Console.cpp.s

include/Utils/Shader.o: include/Utils/Shader.cpp.o
.PHONY : include/Utils/Shader.o

# target to build an object file
include/Utils/Shader.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/earth_sim.dir/build.make CMakeFiles/earth_sim.dir/include/Utils/Shader.cpp.o
.PHONY : include/Utils/Shader.cpp.o

include/Utils/Shader.i: include/Utils/Shader.cpp.i
.PHONY : include/Utils/Shader.i

# target to preprocess a source file
include/Utils/Shader.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/earth_sim.dir/build.make CMakeFiles/earth_sim.dir/include/Utils/Shader.cpp.i
.PHONY : include/Utils/Shader.cpp.i

include/Utils/Shader.s: include/Utils/Shader.cpp.s
.PHONY : include/Utils/Shader.s

# target to generate assembly for a file
include/Utils/Shader.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/earth_sim.dir/build.make CMakeFiles/earth_sim.dir/include/Utils/Shader.cpp.s
.PHONY : include/Utils/Shader.cpp.s

include/Utils/Timer.o: include/Utils/Timer.cpp.o
.PHONY : include/Utils/Timer.o

# target to build an object file
include/Utils/Timer.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/earth_sim.dir/build.make CMakeFiles/earth_sim.dir/include/Utils/Timer.cpp.o
.PHONY : include/Utils/Timer.cpp.o

include/Utils/Timer.i: include/Utils/Timer.cpp.i
.PHONY : include/Utils/Timer.i

# target to preprocess a source file
include/Utils/Timer.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/earth_sim.dir/build.make CMakeFiles/earth_sim.dir/include/Utils/Timer.cpp.i
.PHONY : include/Utils/Timer.cpp.i

include/Utils/Timer.s: include/Utils/Timer.cpp.s
.PHONY : include/Utils/Timer.s

# target to generate assembly for a file
include/Utils/Timer.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/earth_sim.dir/build.make CMakeFiles/earth_sim.dir/include/Utils/Timer.cpp.s
.PHONY : include/Utils/Timer.cpp.s

include/Utils/Window.o: include/Utils/Window.cpp.o
.PHONY : include/Utils/Window.o

# target to build an object file
include/Utils/Window.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/earth_sim.dir/build.make CMakeFiles/earth_sim.dir/include/Utils/Window.cpp.o
.PHONY : include/Utils/Window.cpp.o

include/Utils/Window.i: include/Utils/Window.cpp.i
.PHONY : include/Utils/Window.i

# target to preprocess a source file
include/Utils/Window.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/earth_sim.dir/build.make CMakeFiles/earth_sim.dir/include/Utils/Window.cpp.i
.PHONY : include/Utils/Window.cpp.i

include/Utils/Window.s: include/Utils/Window.cpp.s
.PHONY : include/Utils/Window.s

# target to generate assembly for a file
include/Utils/Window.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/earth_sim.dir/build.make CMakeFiles/earth_sim.dir/include/Utils/Window.cpp.s
.PHONY : include/Utils/Window.cpp.s

include/static/wgs84.o: include/static/wgs84.cpp.o
.PHONY : include/static/wgs84.o

# target to build an object file
include/static/wgs84.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/earth_sim.dir/build.make CMakeFiles/earth_sim.dir/include/static/wgs84.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/wgs_test.dir/build.make CMakeFiles/wgs_test.dir/include/static/wgs84.cpp.o
.PHONY : include/static/wgs84.cpp.o

include/static/wgs84.i: include/static/wgs84.cpp.i
.PHONY : include/static/wgs84.i

# target to preprocess a source file
include/static/wgs84.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/earth_sim.dir/build.make CMakeFiles/earth_sim.dir/include/static/wgs84.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/wgs_test.dir/build.make CMakeFiles/wgs_test.dir/include/static/wgs84.cpp.i
.PHONY : include/static/wgs84.cpp.i

include/static/wgs84.s: include/static/wgs84.cpp.s
.PHONY : include/static/wgs84.s

# target to generate assembly for a file
include/static/wgs84.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/earth_sim.dir/build.make CMakeFiles/earth_sim.dir/include/static/wgs84.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/wgs_test.dir/build.make CMakeFiles/wgs_test.dir/include/static/wgs84.cpp.s
.PHONY : include/static/wgs84.cpp.s

src/main.o: src/main.cpp.o
.PHONY : src/main.o

# target to build an object file
src/main.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/earth_sim.dir/build.make CMakeFiles/earth_sim.dir/src/main.cpp.o
.PHONY : src/main.cpp.o

src/main.i: src/main.cpp.i
.PHONY : src/main.i

# target to preprocess a source file
src/main.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/earth_sim.dir/build.make CMakeFiles/earth_sim.dir/src/main.cpp.i
.PHONY : src/main.cpp.i

src/main.s: src/main.cpp.s
.PHONY : src/main.s

# target to generate assembly for a file
src/main.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/earth_sim.dir/build.make CMakeFiles/earth_sim.dir/src/main.cpp.s
.PHONY : src/main.cpp.s

src/wgs_test.o: src/wgs_test.cpp.o
.PHONY : src/wgs_test.o

# target to build an object file
src/wgs_test.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/wgs_test.dir/build.make CMakeFiles/wgs_test.dir/src/wgs_test.cpp.o
.PHONY : src/wgs_test.cpp.o

src/wgs_test.i: src/wgs_test.cpp.i
.PHONY : src/wgs_test.i

# target to preprocess a source file
src/wgs_test.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/wgs_test.dir/build.make CMakeFiles/wgs_test.dir/src/wgs_test.cpp.i
.PHONY : src/wgs_test.cpp.i

src/wgs_test.s: src/wgs_test.cpp.s
.PHONY : src/wgs_test.s

# target to generate assembly for a file
src/wgs_test.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/wgs_test.dir/build.make CMakeFiles/wgs_test.dir/src/wgs_test.cpp.s
.PHONY : src/wgs_test.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... install"
	@echo "... install/local"
	@echo "... install/strip"
	@echo "... list_install_components"
	@echo "... rebuild_cache"
	@echo "... earth_sim"
	@echo "... loader_example"
	@echo "... tinygltf"
	@echo "... wgs_test"
	@echo "... include/Cameras/FirstPersonCamera.o"
	@echo "... include/Cameras/FirstPersonCamera.i"
	@echo "... include/Cameras/FirstPersonCamera.s"
	@echo "... include/Engine.o"
	@echo "... include/Engine.i"
	@echo "... include/Engine.s"
	@echo "... include/Objects/Object.o"
	@echo "... include/Objects/Object.i"
	@echo "... include/Objects/Object.s"
	@echo "... include/Utils/Console.o"
	@echo "... include/Utils/Console.i"
	@echo "... include/Utils/Console.s"
	@echo "... include/Utils/Shader.o"
	@echo "... include/Utils/Shader.i"
	@echo "... include/Utils/Shader.s"
	@echo "... include/Utils/Timer.o"
	@echo "... include/Utils/Timer.i"
	@echo "... include/Utils/Timer.s"
	@echo "... include/Utils/Window.o"
	@echo "... include/Utils/Window.i"
	@echo "... include/Utils/Window.s"
	@echo "... include/static/wgs84.o"
	@echo "... include/static/wgs84.i"
	@echo "... include/static/wgs84.s"
	@echo "... src/main.o"
	@echo "... src/main.i"
	@echo "... src/main.s"
	@echo "... src/wgs_test.o"
	@echo "... src/wgs_test.i"
	@echo "... src/wgs_test.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

