# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.28

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/m/Code/cpp/EarthSim

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/m/Code/cpp/EarthSim

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/m/Code/cpp/EarthSim/CMakeFiles /home/m/Code/cpp/EarthSim//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/m/Code/cpp/EarthSim/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named earth_sim

# Build rule for target.
earth_sim: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 earth_sim
.PHONY : earth_sim

# fast build rule for target.
earth_sim/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/earth_sim.dir/build.make CMakeFiles/earth_sim.dir/build
.PHONY : earth_sim/fast

include/Utils/Console.o: include/Utils/Console.cpp.o
.PHONY : include/Utils/Console.o

# target to build an object file
include/Utils/Console.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/earth_sim.dir/build.make CMakeFiles/earth_sim.dir/include/Utils/Console.cpp.o
.PHONY : include/Utils/Console.cpp.o

include/Utils/Console.i: include/Utils/Console.cpp.i
.PHONY : include/Utils/Console.i

# target to preprocess a source file
include/Utils/Console.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/earth_sim.dir/build.make CMakeFiles/earth_sim.dir/include/Utils/Console.cpp.i
.PHONY : include/Utils/Console.cpp.i

include/Utils/Console.s: include/Utils/Console.cpp.s
.PHONY : include/Utils/Console.s

# target to generate assembly for a file
include/Utils/Console.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/earth_sim.dir/build.make CMakeFiles/earth_sim.dir/include/Utils/Console.cpp.s
.PHONY : include/Utils/Console.cpp.s

include/common/controls.o: include/common/controls.cpp.o
.PHONY : include/common/controls.o

# target to build an object file
include/common/controls.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/earth_sim.dir/build.make CMakeFiles/earth_sim.dir/include/common/controls.cpp.o
.PHONY : include/common/controls.cpp.o

include/common/controls.i: include/common/controls.cpp.i
.PHONY : include/common/controls.i

# target to preprocess a source file
include/common/controls.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/earth_sim.dir/build.make CMakeFiles/earth_sim.dir/include/common/controls.cpp.i
.PHONY : include/common/controls.cpp.i

include/common/controls.s: include/common/controls.cpp.s
.PHONY : include/common/controls.s

# target to generate assembly for a file
include/common/controls.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/earth_sim.dir/build.make CMakeFiles/earth_sim.dir/include/common/controls.cpp.s
.PHONY : include/common/controls.cpp.s

include/common/shader.o: include/common/shader.cpp.o
.PHONY : include/common/shader.o

# target to build an object file
include/common/shader.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/earth_sim.dir/build.make CMakeFiles/earth_sim.dir/include/common/shader.cpp.o
.PHONY : include/common/shader.cpp.o

include/common/shader.i: include/common/shader.cpp.i
.PHONY : include/common/shader.i

# target to preprocess a source file
include/common/shader.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/earth_sim.dir/build.make CMakeFiles/earth_sim.dir/include/common/shader.cpp.i
.PHONY : include/common/shader.cpp.i

include/common/shader.s: include/common/shader.cpp.s
.PHONY : include/common/shader.s

# target to generate assembly for a file
include/common/shader.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/earth_sim.dir/build.make CMakeFiles/earth_sim.dir/include/common/shader.cpp.s
.PHONY : include/common/shader.cpp.s

include/common/text2D.o: include/common/text2D.cpp.o
.PHONY : include/common/text2D.o

# target to build an object file
include/common/text2D.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/earth_sim.dir/build.make CMakeFiles/earth_sim.dir/include/common/text2D.cpp.o
.PHONY : include/common/text2D.cpp.o

include/common/text2D.i: include/common/text2D.cpp.i
.PHONY : include/common/text2D.i

# target to preprocess a source file
include/common/text2D.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/earth_sim.dir/build.make CMakeFiles/earth_sim.dir/include/common/text2D.cpp.i
.PHONY : include/common/text2D.cpp.i

include/common/text2D.s: include/common/text2D.cpp.s
.PHONY : include/common/text2D.s

# target to generate assembly for a file
include/common/text2D.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/earth_sim.dir/build.make CMakeFiles/earth_sim.dir/include/common/text2D.cpp.s
.PHONY : include/common/text2D.cpp.s

include/common/texture.o: include/common/texture.cpp.o
.PHONY : include/common/texture.o

# target to build an object file
include/common/texture.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/earth_sim.dir/build.make CMakeFiles/earth_sim.dir/include/common/texture.cpp.o
.PHONY : include/common/texture.cpp.o

include/common/texture.i: include/common/texture.cpp.i
.PHONY : include/common/texture.i

# target to preprocess a source file
include/common/texture.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/earth_sim.dir/build.make CMakeFiles/earth_sim.dir/include/common/texture.cpp.i
.PHONY : include/common/texture.cpp.i

include/common/texture.s: include/common/texture.cpp.s
.PHONY : include/common/texture.s

# target to generate assembly for a file
include/common/texture.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/earth_sim.dir/build.make CMakeFiles/earth_sim.dir/include/common/texture.cpp.s
.PHONY : include/common/texture.cpp.s

src/main.o: src/main.cpp.o
.PHONY : src/main.o

# target to build an object file
src/main.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/earth_sim.dir/build.make CMakeFiles/earth_sim.dir/src/main.cpp.o
.PHONY : src/main.cpp.o

src/main.i: src/main.cpp.i
.PHONY : src/main.i

# target to preprocess a source file
src/main.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/earth_sim.dir/build.make CMakeFiles/earth_sim.dir/src/main.cpp.i
.PHONY : src/main.cpp.i

src/main.s: src/main.cpp.s
.PHONY : src/main.s

# target to generate assembly for a file
src/main.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/earth_sim.dir/build.make CMakeFiles/earth_sim.dir/src/main.cpp.s
.PHONY : src/main.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... earth_sim"
	@echo "... include/Utils/Console.o"
	@echo "... include/Utils/Console.i"
	@echo "... include/Utils/Console.s"
	@echo "... include/common/controls.o"
	@echo "... include/common/controls.i"
	@echo "... include/common/controls.s"
	@echo "... include/common/shader.o"
	@echo "... include/common/shader.i"
	@echo "... include/common/shader.s"
	@echo "... include/common/text2D.o"
	@echo "... include/common/text2D.i"
	@echo "... include/common/text2D.s"
	@echo "... include/common/texture.o"
	@echo "... include/common/texture.i"
	@echo "... include/common/texture.s"
	@echo "... src/main.o"
	@echo "... src/main.i"
	@echo "... src/main.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

